---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MIsimulation

The goal of MIsimulation is to replicate and extend the simulation study in Kontopantelis and Evangelos (2017)  

## Installation

You can install the source package MIsimulation by changing the path to file with:

``` r
install.packages("/Users/mingyang/MIsimulation_0.1.0.tar.gz", repos = NULL, type="source")
```

## Example

This is a basic example on how to replicate the results in table 2 in Kontopantelis and Evangelos (2017):

```{r example}
library(MIsimulation)
## 1000 samples generated in each iteration with missing rate 0.2 for each variable under MCAR assumption 
## with 10 iterations
sim_MCAR(n = 1000, NSIM = 10, missRate = 0.2, trueValue = log(2), cores = 3)
## 1000 samples generated in each iteration with missing rate 0.2 for each variable under MAR assumption 
## with 10 iterations
sim_MAR(n = 1000, NSIM = 10, missRate = 0.4, trueValue = log(2), cores = 3)
```


